/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.pkg1;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author FAWAD & BRO
 */
public class BorrowerGUI extends javax.swing.JFrame {

    /**
     * Creates new form BorrowerGUI
     */
    String name;
    public BorrowerGUI() {
        initComponents();
    }
    public BorrowerGUI(String name) {
        initComponents();
        this.name=name;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InfoButton = new javax.swing.JButton();
        HoldButton = new javax.swing.JButton();
        SearchTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        SubjectRadioButton = new javax.swing.JRadioButton();
        TitileRadioButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        HoldTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setText("Welcome");

        jLabel2.setText("What do you want to do?");

        InfoButton.setText("View Info");
        InfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InfoButtonMouseClicked(evt);
            }
        });

        HoldButton.setText("Place item on hold");
        HoldButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoldButtonMouseClicked(evt);
            }
        });

        SearchButton.setText("Search book");
        SearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonMouseClicked(evt);
            }
        });

        buttonGroup1.add(SubjectRadioButton);
        SubjectRadioButton.setText("By subject");
        SubjectRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(TitileRadioButton);
        TitileRadioButton.setText("By title");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SearchButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(SubjectRadioButton)
                                        .addGap(10, 10, 10)
                                        .addComponent(TitileRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(InfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49)
                                                .addComponent(jLabel1))
                                            .addComponent(jLabel2)
                                            .addComponent(HoldButton)
                                            .addComponent(HoldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(130, 130, 130)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 224, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InfoButton)
                .addGap(42, 42, 42)
                .addComponent(HoldButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HoldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitileRadioButton)
                    .addComponent(SubjectRadioButton)
                    .addComponent(SearchButton)
                    .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubjectRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectRadioButtonActionPerformed

    private void SearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseClicked
        if(SubjectRadioButton.isSelected())
        {
            connector con=new connector();
            List<Book> names=new ArrayList<Book>();
            String s=SearchTextField.getText();
            names=con.getBooksBySubject(s);
            for(int i=0;i<names.size();i++)
            {
                jTextArea1.append(names.get(i).title);
                jTextArea1.append("  ");
                jTextArea1.append(names.get(i).subject);
                jTextArea1.append("  ");
                String p=String.valueOf(names.get(i).isbn);
                jTextArea1.append(p);
                jTextArea1.append("  ");
                jTextArea1.append(names.get(i).author);
                 jTextArea1.append("\n");
            }
        }
        else if(TitileRadioButton.isSelected())
        {
            connector con=new connector();
            List<Book> names=new ArrayList<Book>();
            String s=SearchTextField.getText();
            names=con.getBooksByTitle(s);
            jTextArea1.setText(" ");
            for(int i=0;i<names.size();i++)
            {
                jTextArea1.append(names.get(i).title);
                jTextArea1.append("  ");
                jTextArea1.append(names.get(i).subject);
                jTextArea1.append("  ");
                String p=String.valueOf(names.get(i).isbn);
                jTextArea1.append(p);
                jTextArea1.append("  ");
                jTextArea1.append(names.get(i).author);
                jTextArea1.append("\n");
            }
        }
    }//GEN-LAST:event_SearchButtonMouseClicked

    private void InfoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoButtonMouseClicked
            connector con=new connector();
            List<Loan> names=new ArrayList<Loan>();
            String s=name;
            names=con.getBorrowerLoanListByName(s);
            jTextArea1.append("Name:\n ");
            jTextArea1.append(names.get(0).LoanUser);
            for(int i=0;i<names.size();i++)
            {
                
                jTextArea1.append(names.get(i).LoanItem);
                jTextArea1.append(" due date:  ");
                String p=String.valueOf(names.get(i).duedate);
                jTextArea1.append(p);
                jTextArea1.append(" issued date:  ");
                String q=String.valueOf(names.get(i).issuedate);
                jTextArea1.append(q);
                jTextArea1.append("\n");
            }
            List<OnHold> hold=new ArrayList<OnHold>();
            hold=con.getOnHoldByName(s);
            for(int i=0;i<names.size();i++)
            {
                jTextArea1.append("On Hold Items:\n ");
                jTextArea1.append(hold.get(i).HoldItem);
                jTextArea1.append("\n");
            }
    }//GEN-LAST:event_InfoButtonMouseClicked

    private void HoldButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoldButtonMouseClicked
            connector con=new connector();
            String BookName=HoldTextField.getText();
            con.insertOnHold(name,BookName);
    }//GEN-LAST:event_HoldButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrowerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HoldButton;
    private javax.swing.JTextField HoldTextField;
    private javax.swing.JButton InfoButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JRadioButton SubjectRadioButton;
    private javax.swing.JRadioButton TitileRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
