/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.pkg1;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author FAWAD & BRO
 */
public class ClerkGUI extends javax.swing.JFrame {

    String name;
    public ClerkGUI() {
        initComponents();
    }
    public ClerkGUI(String name) {
        initComponents();
        this.name=name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddBorrowerButton = new javax.swing.JButton();
        RemoveBorrowerButton = new javax.swing.JButton();
        RenewButton = new javax.swing.JButton();
        PayFineButton = new javax.swing.JButton();
        UpdateBorrowerButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        TitleRadioButton = new javax.swing.JRadioButton();
        SubjectRadioButton = new javax.swing.JRadioButton();
        SearchTextField = new javax.swing.JTextField();
        ViewButton = new javax.swing.JButton();
        HoldButton = new javax.swing.JButton();
        HoldTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        AddBorrowerNameTextField = new javax.swing.JTextField();
        AddBorrowerPasswordTextField = new javax.swing.JTextField();
        RenewItemTextField = new javax.swing.JTextField();
        RemoveBorrowerNameTextField = new javax.swing.JTextField();
        UpdateBorrowerNameTextField = new javax.swing.JTextField();
        PayFineTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CheckOutButton = new javax.swing.JButton();
        LoanNameTextField = new javax.swing.JTextField();
        LoanItemTextField = new javax.swing.JTextField();
        LoanDateTextField = new javax.swing.JTextField();
        ChecinButton = new javax.swing.JButton();
        CheckinNameTextField = new javax.swing.JTextField();
        CheckinItemTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        RenewDateTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        UpdateAddressTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        UpdatephoneTextField = new javax.swing.JTextField();
        IssuedDateTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        CheckoutBookRadioButton = new javax.swing.JRadioButton();
        CheckoutDVDRadioButton = new javax.swing.JRadioButton();
        CheckinBookRadioButton = new javax.swing.JRadioButton();
        CheckinDVDRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome");

        jLabel2.setText("What do you want to do?");

        AddBorrowerButton.setText("Add a borrower");
        AddBorrowerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBorrowerButtonMouseClicked(evt);
            }
        });

        RemoveBorrowerButton.setText("Remove a borrower");
        RemoveBorrowerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveBorrowerButtonMouseClicked(evt);
            }
        });

        RenewButton.setText("Renew Item");
        RenewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RenewButtonMouseClicked(evt);
            }
        });

        PayFineButton.setText("Pay fine");
        PayFineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PayFineButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PayFineButtonMouseEntered(evt);
            }
        });

        UpdateBorrowerButton.setText("Update borrower info");
        UpdateBorrowerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBorrowerButtonMouseClicked(evt);
            }
        });

        SearchButton.setText("Search book");
        SearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonMouseClicked(evt);
            }
        });

        buttonGroup1.add(TitleRadioButton);
        TitleRadioButton.setText("By title");

        buttonGroup1.add(SubjectRadioButton);
        SubjectRadioButton.setText("By subject");

        ViewButton.setText("View Info");
        ViewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewButtonMouseClicked(evt);
            }
        });

        HoldButton.setText("Place item on Hold");
        HoldButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoldButtonMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Name");

        jLabel4.setText("Borrower");

        jLabel5.setText("Name");

        jLabel6.setText("Password");

        jLabel7.setText("Name");

        jLabel8.setText("Name");

        CheckOutButton.setText("Checkout item");
        CheckOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckOutButtonMouseClicked(evt);
            }
        });

        ChecinButton.setText("Checkin item");
        ChecinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChecinButtonMouseClicked(evt);
            }
        });

        jLabel9.setText("Borrower Name");

        jLabel10.setText("Item Title");

        jLabel11.setText("Due Date");

        jLabel12.setText("Borrower Name");

        jLabel13.setText("Item Title");

        jLabel14.setText("New Date");

        jLabel15.setText("Title");

        jLabel16.setText("Address");

        jLabel17.setText("phone");

        jLabel18.setText("Issued Date");

        buttonGroup2.add(CheckoutBookRadioButton);
        CheckoutBookRadioButton.setText("Book");

        buttonGroup2.add(CheckoutDVDRadioButton);
        CheckoutDVDRadioButton.setText("DVD");

        buttonGroup3.add(CheckinBookRadioButton);
        CheckinBookRadioButton.setText("Book");

        buttonGroup3.add(CheckinDVDRadioButton);
        CheckinDVDRadioButton.setText("DVD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(HoldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(HoldButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(AddBorrowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AddBorrowerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AddBorrowerPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(RemoveBorrowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(PayFineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PayFineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel12))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CheckinNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(CheckinItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(IssuedDateTextField)
                                                    .addComponent(LoanDateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                                    .addComponent(LoanItemTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(LoanNameTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                                        .addGap(31, 31, 31))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CheckOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CheckoutBookRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CheckoutDVDRadioButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ChecinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CheckinBookRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CheckinDVDRadioButton)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UpdateBorrowerButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(SearchButton)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(TitleRadioButton)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(SubjectRadioButton)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(242, 242, 242)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel17))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(UpdateBorrowerNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                            .addComponent(UpdateAddressTextField)
                                            .addComponent(UpdatephoneTextField))
                                        .addGap(15, 15, 15))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ViewButton)
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RenewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RenewItemTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                    .addComponent(RenewDateTextField))
                                .addGap(8, 8, 8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RemoveBorrowerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBorrowerButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RenewButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ViewButton)
                        .addComponent(AddBorrowerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddBorrowerPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RenewItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveBorrowerButton)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RemoveBorrowerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(HoldButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HoldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateBorrowerButton)
                            .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(RenewDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PayFineButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PayFineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBorrowerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(UpdateAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SearchButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdatephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(TitleRadioButton)
                    .addComponent(SubjectRadioButton)
                    .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckOutButton)
                            .addComponent(CheckoutBookRadioButton)
                            .addComponent(CheckoutDVDRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoanNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoanItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoanDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IssuedDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChecinButton)
                            .addComponent(CheckinBookRadioButton)
                            .addComponent(CheckinDVDRadioButton))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckinNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckinItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewButtonMouseClicked
            connector con=new connector();
            List<Loan> names=new ArrayList<Loan>();
            String s=name;
            names=con.getBorrowerLoanListByName(s);
            jTextArea1.append("Name:\n ");
            jTextArea1.append(names.get(0).LoanUser);
            for(int i=0;i<names.size();i++)
            {
                
                jTextArea1.append(names.get(i).LoanItem);
                jTextArea1.append(" due date:  ");
                String p=String.valueOf(names.get(i).duedate);
                jTextArea1.append(p);
                jTextArea1.append(" issued date:  ");
                String q=String.valueOf(names.get(i).issuedate);
                jTextArea1.append(q);
                jTextArea1.append("\n");
            }
            List<OnHold> hold=new ArrayList<OnHold>();
            hold=con.getOnHoldByName(s);
            for(int i=0;i<names.size();i++)
            {
                jTextArea1.append("On Hold Items:\n ");
                jTextArea1.append(hold.get(i).HoldItem);
                jTextArea1.append("\n");
            }
    }//GEN-LAST:event_ViewButtonMouseClicked

    private void HoldButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoldButtonMouseClicked
            connector con=new connector();
            String BookName=HoldTextField.getText();
            con.insertOnHold(name,BookName);
            JOptionPane.showMessageDialog(null,"Done","Insert succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_HoldButtonMouseClicked

    private void SearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseClicked
        if(SubjectRadioButton.isSelected())
        {
            connector con=new connector();
            List<Book> names=new ArrayList<Book>();
            String s=SearchTextField.getText();
            names=con.getBooksBySubject(s);
            for(int i=0;i<names.size();i++)
            {
                jTextArea1.append(names.get(i).title);
                jTextArea1.append("  ");
                jTextArea1.append(names.get(i).subject);
                jTextArea1.append("  ");
                String p=String.valueOf(names.get(i).isbn);
                jTextArea1.append(p);
                jTextArea1.append("  ");
                jTextArea1.append(names.get(i).author);
                 jTextArea1.append("\n");
            }
        }
        else if(TitleRadioButton.isSelected())
        {
            connector con=new connector();
            List<Book> names=new ArrayList<Book>();
            String s=SearchTextField.getText();
            names=con.getBooksByTitle(s);
            jTextArea1.setText(" ");
            for(int i=0;i<names.size();i++)
            {
                jTextArea1.append(names.get(i).title);
                jTextArea1.append("  ");
                jTextArea1.append(names.get(i).subject);
                jTextArea1.append("  ");
                String p=String.valueOf(names.get(i).isbn);
                jTextArea1.append(p);
                jTextArea1.append("  ");
                jTextArea1.append(names.get(i).author);
                jTextArea1.append("\n");
            }
        }
    }//GEN-LAST:event_SearchButtonMouseClicked

    private void RenewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RenewButtonMouseClicked
        String date = RenewDateTextField.getText();
        String name = RenewItemTextField.getText();
        connector con=new connector();
        con.ExtendDate(name, date);
        JOptionPane.showMessageDialog(null,"Done","Renew succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_RenewButtonMouseClicked

    private void PayFineButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayFineButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PayFineButtonMouseEntered

    private void PayFineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayFineButtonMouseClicked
        String name = PayFineTextField.getText();
        connector con=new connector();
        con.PayFine(name);
        JOptionPane.showMessageDialog(null,"Done","Fine Paid succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_PayFineButtonMouseClicked

    private void AddBorrowerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBorrowerButtonMouseClicked
        String name = AddBorrowerNameTextField.getText();
        String p = AddBorrowerPasswordTextField.getText();
        connector con=new connector();
        con.insertBorrower(name, p);
        JOptionPane.showMessageDialog(null,"Done","Borrower inserted succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_AddBorrowerButtonMouseClicked

    private void RemoveBorrowerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveBorrowerButtonMouseClicked
        String name = RemoveBorrowerNameTextField.getText();
        connector con=new connector();
        con.deleteBorrower(name);
        JOptionPane.showMessageDialog(null,"Done","Borrower deleted succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_RemoveBorrowerButtonMouseClicked

    private void UpdateBorrowerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBorrowerButtonMouseClicked
        String name = UpdateBorrowerNameTextField.getText();
        String a = UpdateAddressTextField.getText();
        String p = UpdatephoneTextField.getText();
        connector con=new connector();
        con.updateBorrower(name,a,p);
        JOptionPane.showMessageDialog(null,"Done","Borrower updated succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_UpdateBorrowerButtonMouseClicked

    private void CheckOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckOutButtonMouseClicked
        connector con=new connector();
        String is =IssuedDateTextField.getText();
        if(CheckoutBookRadioButton.isSelected())
        {
        con.IssueBook(is);
        }
        else if(CheckoutDVDRadioButton.isSelected())
        {
           con.IssueDVD(is); 
        }
        else
        {
        JOptionPane.showMessageDialog(null,"Done","Checkout Item failed",JOptionPane.PLAIN_MESSAGE);
        return;
        }
        String name = LoanNameTextField.getText();
        String i = LoanItemTextField.getText();
        String d = LoanDateTextField.getText();
        con.insertLoan(name,i,d,is);
        
        JOptionPane.showMessageDialog(null,"Done","Checkout Item succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_CheckOutButtonMouseClicked

    private void ChecinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChecinButtonMouseClicked
        connector con=new connector();
        String is =IssuedDateTextField.getText();
        if(CheckinBookRadioButton.isSelected())
        {
        con.UnIssueBook(is);
        }
        else if(CheckinDVDRadioButton.isSelected())
        {
           con.UnIssueDVD(is); 
        }
        else
        {
        JOptionPane.showMessageDialog(null,"Done","Checkin Item failed",JOptionPane.PLAIN_MESSAGE);
        return;
        }
        String name = CheckinNameTextField.getText();
        String i = CheckinItemTextField.getText();
        
        JOptionPane.showMessageDialog(null,"Done","Checkin Item Successful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_ChecinButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClerkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClerkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClerkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClerkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClerkGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBorrowerButton;
    private javax.swing.JTextField AddBorrowerNameTextField;
    private javax.swing.JTextField AddBorrowerPasswordTextField;
    private javax.swing.JButton ChecinButton;
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JRadioButton CheckinBookRadioButton;
    private javax.swing.JRadioButton CheckinDVDRadioButton;
    private javax.swing.JTextField CheckinItemTextField;
    private javax.swing.JTextField CheckinNameTextField;
    private javax.swing.JRadioButton CheckoutBookRadioButton;
    private javax.swing.JRadioButton CheckoutDVDRadioButton;
    private javax.swing.JButton HoldButton;
    private javax.swing.JTextField HoldTextField;
    private javax.swing.JTextField IssuedDateTextField;
    private javax.swing.JTextField LoanDateTextField;
    private javax.swing.JTextField LoanItemTextField;
    private javax.swing.JTextField LoanNameTextField;
    private javax.swing.JButton PayFineButton;
    private javax.swing.JTextField PayFineTextField;
    private javax.swing.JButton RemoveBorrowerButton;
    private javax.swing.JTextField RemoveBorrowerNameTextField;
    private javax.swing.JButton RenewButton;
    private javax.swing.JTextField RenewDateTextField;
    private javax.swing.JTextField RenewItemTextField;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JRadioButton SubjectRadioButton;
    private javax.swing.JRadioButton TitleRadioButton;
    private javax.swing.JTextField UpdateAddressTextField;
    private javax.swing.JButton UpdateBorrowerButton;
    private javax.swing.JTextField UpdateBorrowerNameTextField;
    private javax.swing.JTextField UpdatephoneTextField;
    private javax.swing.JButton ViewButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
