/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.pkg1;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author FAWAD & BRO
 */
public class LibrarianGUI extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianGUI
     */
    String name;
    public LibrarianGUI() {
        initComponents();
    }
    public LibrarianGUI(String name) {
        initComponents();
        this.name=name;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        ViewInfoButton = new javax.swing.JButton();
        HoldButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        HoldTitleTextField = new javax.swing.JTextField();
        RenewButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RenewNameTextField = new javax.swing.JTextField();
        RenewDateTextField = new javax.swing.JTextField();
        PayFineButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        PayFineTextField = new javax.swing.JTextField();
        AddBorrowerButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AddBorrowerTextField = new javax.swing.JTextField();
        AddBorrowerPasswordTextField = new javax.swing.JTextField();
        UpdateBorrowerButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        UpdateBorrowerNameTextField = new javax.swing.JTextField();
        UpdateAddressTextField = new javax.swing.JTextField();
        UpdatePhoneTextField = new javax.swing.JTextField();
        DeleteBorrowerButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        DeleteBorrowerTextField = new javax.swing.JTextField();
        SearchBookButton = new javax.swing.JButton();
        SearchTitleRadioButton = new javax.swing.JRadioButton();
        SearchSubjectRadioButton = new javax.swing.JRadioButton();
        SearchBookTextField = new javax.swing.JTextField();
        CheckoutButton = new javax.swing.JButton();
        CheckoutBookRadioButton = new javax.swing.JRadioButton();
        CheckoutDVDRadioButton = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CheckoutNameTextField = new javax.swing.JTextField();
        ChecktitleTextField = new javax.swing.JTextField();
        CheckoutDurDateTextField = new javax.swing.JTextField();
        CheckoutIssueDateTextField = new javax.swing.JTextField();
        CheckinButton = new javax.swing.JButton();
        CheckinBookRadioButton = new javax.swing.JRadioButton();
        CheckinDVDRadioButton = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CheckinBorrowerTextField = new javax.swing.JTextField();
        CheckinItemTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        AddDVDButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        AddDVDTitleTextField = new javax.swing.JTextField();
        AddBookAuthorTextField = new javax.swing.JTextField();
        AddDVDSubjectTextField = new javax.swing.JTextField();
        RemoveDVDButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        RemoveDVDTitleTextField = new javax.swing.JTextField();
        EditDVDinfoButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        EditDVDTitleTextField = new javax.swing.JTextField();
        AddBookTitleTextField = new javax.swing.JTextField();
        EditDVDSubjectTextField = new javax.swing.JTextField();
        AddBookButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        AddBookSubjectTextField = new javax.swing.JTextField();
        AddBookisbnTextField = new javax.swing.JTextField();
        RemoveBookButton = new javax.swing.JButton();
        RemoveBookTitleTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        UpdateBookAuthorTextField = new javax.swing.JTextField();
        UpdateBookTitleTextField = new javax.swing.JTextField();
        UpdateBookInfoButton = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        UpdateBookSubjectTextField = new javax.swing.JTextField();
        UpdateBookisbnTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome");

        ViewInfoButton.setText("View Info");
        ViewInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewInfoButtonMouseClicked(evt);
            }
        });

        HoldButton.setText("Place Item on Hold");
        HoldButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoldButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("Title");

        RenewButton.setText("Renew Item");
        RenewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RenewButtonMouseClicked(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("New Date");

        PayFineButton.setText("Pay Fine");
        PayFineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PayFineButtonMouseClicked(evt);
            }
        });

        jLabel5.setText("Borrower");

        AddBorrowerButton.setText("Add a Borrower");
        AddBorrowerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBorrowerButtonMouseClicked(evt);
            }
        });

        jLabel6.setText("Name");

        jLabel7.setText("Password");

        UpdateBorrowerButton.setText("Update Borrower Info");
        UpdateBorrowerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBorrowerButtonMouseClicked(evt);
            }
        });

        jLabel8.setText("Name");

        jLabel9.setText("Address");

        jLabel10.setText("Phone");

        DeleteBorrowerButton.setText("Delete Borrower");
        DeleteBorrowerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBorrowerButtonMouseClicked(evt);
            }
        });

        jLabel11.setText("Name");

        SearchBookButton.setText("Search Book");
        SearchBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBookButtonMouseClicked(evt);
            }
        });

        buttonGroup1.add(SearchTitleRadioButton);
        SearchTitleRadioButton.setText("By Title");

        buttonGroup1.add(SearchSubjectRadioButton);
        SearchSubjectRadioButton.setText("By Subject");

        CheckoutButton.setText("Checkout Item");
        CheckoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckoutButtonMouseClicked(evt);
            }
        });

        buttonGroup3.add(CheckoutBookRadioButton);
        CheckoutBookRadioButton.setText("Book");

        buttonGroup3.add(CheckoutDVDRadioButton);
        CheckoutDVDRadioButton.setText("DVD");

        jLabel12.setText("Borrower Name");

        jLabel13.setText("Item Title");

        jLabel14.setText("Due Date");

        jLabel15.setText("Issue Date");

        CheckinButton.setText("Checkin Item");

        buttonGroup2.add(CheckinBookRadioButton);
        CheckinBookRadioButton.setText("Book");

        buttonGroup2.add(CheckinDVDRadioButton);
        CheckinDVDRadioButton.setText("DVD");

        jLabel16.setText("Borrower Name");

        jLabel17.setText("Item Title");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        AddDVDButton.setText("Add DVD");
        AddDVDButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddDVDButtonMouseClicked(evt);
            }
        });

        jLabel18.setText("Title");

        jLabel19.setText("Author");

        jLabel20.setText("Subject");

        RemoveDVDButton.setText("Remove DVD");
        RemoveDVDButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveDVDButtonMouseClicked(evt);
            }
        });

        jLabel21.setText("Title");

        EditDVDinfoButton.setText("Edit DVD info");
        EditDVDinfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditDVDinfoButtonMouseClicked(evt);
            }
        });

        jLabel22.setText("Title");

        jLabel23.setText("Title");

        jLabel24.setText("Subject");

        AddBookButton.setText("Add Book");
        AddBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBookButtonMouseClicked(evt);
            }
        });

        jLabel25.setText("Title");

        jLabel26.setText("Subject");

        jLabel27.setText("isbn");

        RemoveBookButton.setText("Remove Book");
        RemoveBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveBookButtonMouseClicked(evt);
            }
        });

        jLabel28.setText("Author");

        UpdateBookInfoButton.setText("Update Book info");
        UpdateBookInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBookInfoButtonMouseClicked(evt);
            }
        });

        jLabel29.setText("Title");

        jLabel30.setText("Subject");

        jLabel31.setText("isbn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(RenewNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(RenewDateTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(HoldTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ViewInfoButton)
                                    .addComponent(HoldButton)
                                    .addComponent(RenewButton))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PayFineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(PayFineButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(SearchBookButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(SearchTitleRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchSubjectRadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(SearchBookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateBorrowerButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UpdateBorrowerNameTextField)
                                    .addComponent(UpdateAddressTextField)
                                    .addComponent(UpdatePhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(AddBorrowerButton)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(AddBorrowerTextField)
                                                .addComponent(AddBorrowerPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(DeleteBorrowerButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DeleteBorrowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CheckinBookRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CheckinDVDRadioButton))
                                    .addComponent(CheckoutButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(CheckoutBookRadioButton)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(CheckoutDVDRadioButton)
                                            .addComponent(ChecktitleTextField)
                                            .addComponent(CheckoutDurDateTextField)
                                            .addComponent(CheckoutIssueDateTextField)
                                            .addComponent(CheckoutNameTextField)))
                                    .addComponent(CheckinButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel17)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(CheckinItemTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                            .addComponent(CheckinBorrowerTextField))))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddDVDButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AddDVDSubjectTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                    .addComponent(AddDVDTitleTextField)))
                            .addComponent(RemoveDVDButton)
                            .addComponent(EditDVDinfoButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoveDVDTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(EditDVDTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EditDVDSubjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(18, 18, 18)
                                        .addComponent(AddBookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(AddBookButton)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel26)
                                            .addGap(1, 1, 1)
                                            .addComponent(AddBookSubjectTextField))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel27))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(AddBookAuthorTextField)
                                                .addComponent(AddBookisbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateBookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(RemoveBookButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RemoveBookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UpdateBookInfoButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel30)
                                    .addGap(1, 1, 1)
                                    .addComponent(UpdateBookSubjectTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel31))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(UpdateBookAuthorTextField)
                                        .addComponent(UpdateBookisbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewInfoButton)
                            .addComponent(PayFineButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(PayFineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(HoldButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(HoldTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(RenewButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(RenewNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(RenewDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddBorrowerButton)
                            .addComponent(CheckoutButton)
                            .addComponent(AddDVDButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(AddBorrowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckoutBookRadioButton)
                            .addComponent(CheckoutDVDRadioButton)
                            .addComponent(jLabel18)
                            .addComponent(AddDVDTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(AddBorrowerPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(CheckoutNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(AddDVDSubjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdateBorrowerButton)
                            .addComponent(SearchBookButton)
                            .addComponent(jLabel13)
                            .addComponent(ChecktitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemoveDVDButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(UpdateBorrowerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchTitleRadioButton)
                            .addComponent(SearchSubjectRadioButton)
                            .addComponent(jLabel14)
                            .addComponent(CheckoutDurDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(RemoveDVDTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(UpdateAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchBookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(CheckoutIssueDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditDVDinfoButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(UpdatePhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckinButton)
                            .addComponent(jLabel22)
                            .addComponent(EditDVDTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeleteBorrowerButton)
                            .addComponent(CheckinBookRadioButton)
                            .addComponent(CheckinDVDRadioButton)
                            .addComponent(jLabel24)
                            .addComponent(EditDVDSubjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(DeleteBorrowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(CheckinBorrowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddBookButton))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25)
                                            .addComponent(AddBookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel26)
                                            .addComponent(AddBookSubjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel19)
                                            .addComponent(AddBookAuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel27)
                                            .addComponent(AddBookisbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(RemoveBookButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RemoveBookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(UpdateBookInfoButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(UpdateBookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel30)
                                            .addComponent(UpdateBookSubjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel28)
                                            .addComponent(UpdateBookAuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel31)
                                            .addComponent(UpdateBookisbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel17)
                                            .addComponent(CheckinItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewInfoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewInfoButtonMouseClicked
                    connector con=new connector();
            List<Loan> names=new ArrayList<Loan>();
            String s=name;
            names=con.getBorrowerLoanListByName(s);
            jTextArea1.append("Name:\n ");
            jTextArea1.append(names.get(0).LoanUser);
            for(int i=0;i<names.size();i++)
            {
                
                jTextArea1.append(names.get(i).LoanItem);
                jTextArea1.append(" due date:  ");
                String p=String.valueOf(names.get(i).duedate);
                jTextArea1.append(p);
                jTextArea1.append(" issued date:  ");
                String q=String.valueOf(names.get(i).issuedate);
                jTextArea1.append(q);
                jTextArea1.append("\n");
            }
            List<OnHold> hold=new ArrayList<OnHold>();
            hold=con.getOnHoldByName(s);
            for(int i=0;i<names.size();i++)
            {
                jTextArea1.append("On Hold Items:\n ");
                jTextArea1.append(hold.get(i).HoldItem);
                jTextArea1.append("\n");
            }
    }//GEN-LAST:event_ViewInfoButtonMouseClicked

    private void HoldButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoldButtonMouseClicked
            connector con=new connector();
            String BookName=HoldTitleTextField.getText();
            con.insertOnHold(name,BookName);
            JOptionPane.showMessageDialog(null,"Done","Insert succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_HoldButtonMouseClicked

    private void RenewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RenewButtonMouseClicked
        String name = RenewNameTextField.getText();
        String date = RenewDateTextField.getText();
        connector con=new connector();
        con.ExtendDate(name, date);
        JOptionPane.showMessageDialog(null,"Done","Renew succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_RenewButtonMouseClicked

    private void PayFineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayFineButtonMouseClicked
        String name = PayFineTextField.getText();
        connector con=new connector();
        con.PayFine(name);
        JOptionPane.showMessageDialog(null,"Done","Fine Paid succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_PayFineButtonMouseClicked

    private void SearchBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBookButtonMouseClicked
        if(SearchSubjectRadioButton.isSelected())
        {
            connector con=new connector();
            List<Book> names=new ArrayList<Book>();
            String s=SearchBookTextField.getText();
            names=con.getBooksBySubject(s);
            for(int i=0;i<names.size();i++)
            {
                jTextArea1.append(names.get(i).title);
                jTextArea1.append("  ");
                jTextArea1.append(names.get(i).subject);
                jTextArea1.append("  ");
                String p=String.valueOf(names.get(i).isbn);
                jTextArea1.append(p);
                jTextArea1.append("  ");
                jTextArea1.append(names.get(i).author);
                 jTextArea1.append("\n");
            }
        }
        else if(SearchTitleRadioButton.isSelected())
        {
            connector con=new connector();
            List<Book> names=new ArrayList<Book>();
            String s=SearchBookTextField.getText();
            names=con.getBooksByTitle(s);
            jTextArea1.setText(" ");
            for(int i=0;i<names.size();i++)
            {
                jTextArea1.append(names.get(i).title);
                jTextArea1.append("  ");
                jTextArea1.append(names.get(i).subject);
                jTextArea1.append("  ");
                String p=String.valueOf(names.get(i).isbn);
                jTextArea1.append(p);
                jTextArea1.append("  ");
                jTextArea1.append(names.get(i).author);
                jTextArea1.append("\n");
            }
        }
    }//GEN-LAST:event_SearchBookButtonMouseClicked

    private void AddBorrowerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBorrowerButtonMouseClicked
        String name = AddBorrowerTextField.getText();
        String p = AddBorrowerPasswordTextField.getText();
        connector con=new connector();
        con.insertBorrower(name, p);
        JOptionPane.showMessageDialog(null,"Done","Borrower inserted succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_AddBorrowerButtonMouseClicked

    private void UpdateBorrowerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBorrowerButtonMouseClicked
       String name = UpdateBorrowerNameTextField.getText();
        String a = UpdateAddressTextField.getText();
        String p = UpdatePhoneTextField.getText();
        connector con=new connector();
        con.updateBorrower(name,a,p);
        JOptionPane.showMessageDialog(null,"Done","Borrower updated succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_UpdateBorrowerButtonMouseClicked

    private void DeleteBorrowerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBorrowerButtonMouseClicked
        String name = DeleteBorrowerTextField.getText();
        connector con=new connector();
        con.deleteBorrower(name);
        JOptionPane.showMessageDialog(null,"Done","Borrower deleted succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_DeleteBorrowerButtonMouseClicked

    private void CheckoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckoutButtonMouseClicked
        connector con=new connector();
        String is =CheckoutIssueDateTextField.getText();
        if(CheckoutBookRadioButton.isSelected())
        {
        con.IssueBook(is);
        }
        else if(CheckoutDVDRadioButton.isSelected())
        {
           con.IssueDVD(is); 
        }
        else
        {
        JOptionPane.showMessageDialog(null,"Done","Checkout Item failed",JOptionPane.PLAIN_MESSAGE);
        return;
        }
        String name = CheckoutNameTextField.getText();
        String i = ChecktitleTextField.getText();
        String d = CheckoutDurDateTextField.getText();
        con.insertLoan(name,i,d,is);
        
        JOptionPane.showMessageDialog(null,"Done","Checkout Item succesful",JOptionPane.PLAIN_MESSAGE);    }//GEN-LAST:event_CheckoutButtonMouseClicked

    private void AddDVDButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddDVDButtonMouseClicked
        String t = AddDVDTitleTextField.getText();
        String s = AddDVDSubjectTextField.getText();
        connector con=new connector();
        con.insertDVD(t, s,false);
        JOptionPane.showMessageDialog(null,"Done","DVD inserted succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_AddDVDButtonMouseClicked

    private void RemoveDVDButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveDVDButtonMouseClicked
        String t = RemoveDVDTitleTextField.getText();
        connector con=new connector();
        con.deleteDVD(t);
        JOptionPane.showMessageDialog(null,"Done","DVD deleted succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_RemoveDVDButtonMouseClicked

    private void EditDVDinfoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditDVDinfoButtonMouseClicked
        String t = EditDVDTitleTextField.getText();
        String s = EditDVDSubjectTextField.getText();
        connector con=new connector();
        con.updateDVD(t,s,false);
        JOptionPane.showMessageDialog(null,"Done","DVD updated succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_EditDVDinfoButtonMouseClicked

    private void AddBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBookButtonMouseClicked
        String t = AddBookTitleTextField.getText();
        String s = AddBookSubjectTextField.getText();
        String a = AddBookAuthorTextField.getText();
        int i = Integer.valueOf(AddBookisbnTextField.getText());
        connector con=new connector();
        con.insertBook(t,s,i,a);
        JOptionPane.showMessageDialog(null,"Done","Book Inserted succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_AddBookButtonMouseClicked

    private void RemoveBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveBookButtonMouseClicked
        String t = RemoveBookTitleTextField.getText();
        connector con=new connector();
        con.deleteBook(t);
        JOptionPane.showMessageDialog(null,"Done","Book Removed succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_RemoveBookButtonMouseClicked

    private void UpdateBookInfoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBookInfoButtonMouseClicked
       String t = UpdateBookTitleTextField.getText();
        String s = UpdateBookSubjectTextField.getText();
        String a = UpdateBookAuthorTextField.getText();
        int i = Integer.valueOf(UpdateBookisbnTextField.getText());
        connector con=new connector();
        con.updateBook(t,s,i,a,false);
        JOptionPane.showMessageDialog(null,"Done","Book updated succesful",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_UpdateBookInfoButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddBookAuthorTextField;
    private javax.swing.JButton AddBookButton;
    private javax.swing.JTextField AddBookSubjectTextField;
    private javax.swing.JTextField AddBookTitleTextField;
    private javax.swing.JTextField AddBookisbnTextField;
    private javax.swing.JButton AddBorrowerButton;
    private javax.swing.JTextField AddBorrowerPasswordTextField;
    private javax.swing.JTextField AddBorrowerTextField;
    private javax.swing.JButton AddDVDButton;
    private javax.swing.JTextField AddDVDSubjectTextField;
    private javax.swing.JTextField AddDVDTitleTextField;
    private javax.swing.JRadioButton CheckinBookRadioButton;
    private javax.swing.JTextField CheckinBorrowerTextField;
    private javax.swing.JButton CheckinButton;
    private javax.swing.JRadioButton CheckinDVDRadioButton;
    private javax.swing.JTextField CheckinItemTextField;
    private javax.swing.JRadioButton CheckoutBookRadioButton;
    private javax.swing.JButton CheckoutButton;
    private javax.swing.JRadioButton CheckoutDVDRadioButton;
    private javax.swing.JTextField CheckoutDurDateTextField;
    private javax.swing.JTextField CheckoutIssueDateTextField;
    private javax.swing.JTextField CheckoutNameTextField;
    private javax.swing.JTextField ChecktitleTextField;
    private javax.swing.JButton DeleteBorrowerButton;
    private javax.swing.JTextField DeleteBorrowerTextField;
    private javax.swing.JTextField EditDVDSubjectTextField;
    private javax.swing.JTextField EditDVDTitleTextField;
    private javax.swing.JButton EditDVDinfoButton;
    private javax.swing.JButton HoldButton;
    private javax.swing.JTextField HoldTitleTextField;
    private javax.swing.JButton PayFineButton;
    private javax.swing.JTextField PayFineTextField;
    private javax.swing.JButton RemoveBookButton;
    private javax.swing.JTextField RemoveBookTitleTextField;
    private javax.swing.JButton RemoveDVDButton;
    private javax.swing.JTextField RemoveDVDTitleTextField;
    private javax.swing.JButton RenewButton;
    private javax.swing.JTextField RenewDateTextField;
    private javax.swing.JTextField RenewNameTextField;
    private javax.swing.JButton SearchBookButton;
    private javax.swing.JTextField SearchBookTextField;
    private javax.swing.JRadioButton SearchSubjectRadioButton;
    private javax.swing.JRadioButton SearchTitleRadioButton;
    private javax.swing.JTextField UpdateAddressTextField;
    private javax.swing.JTextField UpdateBookAuthorTextField;
    private javax.swing.JButton UpdateBookInfoButton;
    private javax.swing.JTextField UpdateBookSubjectTextField;
    private javax.swing.JTextField UpdateBookTitleTextField;
    private javax.swing.JTextField UpdateBookisbnTextField;
    private javax.swing.JButton UpdateBorrowerButton;
    private javax.swing.JTextField UpdateBorrowerNameTextField;
    private javax.swing.JTextField UpdatePhoneTextField;
    private javax.swing.JButton ViewInfoButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
