/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.pkg1;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author FAWAD & BRO
 */
public class ClerkGUI extends javax.swing.JFrame {

    int id;
    public ClerkGUI() {
        initComponents();
    }
    public ClerkGUI(int id) {
        initComponents();
        this.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddBorrowerButton = new javax.swing.JButton();
        RemoveBorrowerButton = new javax.swing.JButton();
        RenewButton = new javax.swing.JButton();
        PayFineButton = new javax.swing.JButton();
        UpdateBorrowerButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        TitleRadioButton = new javax.swing.JRadioButton();
        SubjectRadioButton = new javax.swing.JRadioButton();
        SearchTextField = new javax.swing.JTextField();
        ViewButton = new javax.swing.JButton();
        HoldButton = new javax.swing.JButton();
        HoldTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        RenewItemTextField = new javax.swing.JTextField();
        RemoveBorrowerNameTextField = new javax.swing.JTextField();
        UpdateBorrowerNameTextField = new javax.swing.JTextField();
        PayFineTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CheckOutButton = new javax.swing.JButton();
        LoanNameTextField = new javax.swing.JTextField();
        LoanItemTextField = new javax.swing.JTextField();
        LoanDateTextField = new javax.swing.JTextField();
        ChecinButton = new javax.swing.JButton();
        CheckinNameTextField = new javax.swing.JTextField();
        CheckinItemTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        RenewDateTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        UpdateAddressTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        UpdatephoneTextField = new javax.swing.JTextField();
        IssuedDateTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ItemidTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome");

        jLabel2.setText("What do you want to do?");

        AddBorrowerButton.setText("Add a borrower");
        AddBorrowerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBorrowerButtonMouseClicked(evt);
            }
        });

        RemoveBorrowerButton.setText("Remove a borrower");
        RemoveBorrowerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveBorrowerButtonMouseClicked(evt);
            }
        });

        RenewButton.setText("Renew Item");
        RenewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RenewButtonMouseClicked(evt);
            }
        });

        PayFineButton.setText("Pay fine");
        PayFineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PayFineButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PayFineButtonMouseEntered(evt);
            }
        });

        UpdateBorrowerButton.setText("Update borrower info");
        UpdateBorrowerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBorrowerButtonMouseClicked(evt);
            }
        });

        SearchButton.setText("Search book");
        SearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonMouseClicked(evt);
            }
        });

        buttonGroup1.add(TitleRadioButton);
        TitleRadioButton.setText("By title");

        buttonGroup1.add(SubjectRadioButton);
        SubjectRadioButton.setText("By subject");

        ViewButton.setText("View Info");
        ViewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewButtonMouseClicked(evt);
            }
        });

        HoldButton.setText("Place item on Hold");
        HoldButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoldButtonMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Borrower id");

        jLabel4.setText("Borrower id");

        jLabel7.setText("id");

        jLabel8.setText("id");

        CheckOutButton.setText("Checkout item");
        CheckOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckOutButtonMouseClicked(evt);
            }
        });

        ChecinButton.setText("Checkin item");
        ChecinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChecinButtonMouseClicked(evt);
            }
        });

        jLabel9.setText("Borrower Id");

        jLabel10.setText("Item Id");

        jLabel11.setText("Due Date");

        jLabel12.setText("Borrower Id");

        jLabel13.setText("Item Id");

        jLabel14.setText("New Date");

        jLabel15.setText("Id");

        jLabel16.setText("Address");

        jLabel17.setText("phone");

        jLabel18.setText("Issued Date");

        jLabel19.setText("Item id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(HoldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(HoldButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemidTextField)
                            .addComponent(RenewItemTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(AddBorrowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RemoveBorrowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(PayFineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PayFineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CheckinNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CheckinItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(IssuedDateTextField)
                                            .addComponent(LoanDateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                            .addComponent(LoanItemTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LoanNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(CheckOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ChecinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UpdateBorrowerButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(SearchButton)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(TitleRadioButton)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(SubjectRadioButton)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(242, 242, 242)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel17))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(UpdateBorrowerNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                            .addComponent(UpdateAddressTextField)
                                            .addComponent(UpdatephoneTextField))
                                        .addGap(15, 15, 15))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RenewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ViewButton)
                                .addGap(129, 129, 129)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RenewDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RemoveBorrowerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddBorrowerButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)))
                    .addComponent(RenewButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RemoveBorrowerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RenewItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ItemidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RemoveBorrowerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(HoldButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(UpdateBorrowerButton)
                                .addComponent(jLabel15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(RenewDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PayFineButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PayFineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBorrowerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(UpdateAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SearchButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdatephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(TitleRadioButton)
                    .addComponent(SubjectRadioButton)
                    .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CheckOutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoanNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoanItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoanDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IssuedDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChecinButton)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckinNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckinItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewButtonMouseClicked
         
            int row=0;
            jTextArea1.append("Name:\n ");
            for(int i=0;i<Library.getInstance().borrowers.size();i++)
            {
                if(Library.getInstance().borrowers.get(i).id==id)
                    row=i;
            }
            jTextArea1.append(Library.getInstance().borrowers.get(row).name);
            jTextArea1.append(" password:  ");
            jTextArea1.append(Library.getInstance().borrowers.get(row).password);
            jTextArea1.append(" Address:  ");
            jTextArea1.append(Library.getInstance().borrowers.get(row).address);
            jTextArea1.append(" Phone:  ");
            jTextArea1.append(Library.getInstance().borrowers.get(row).phone);
            jTextArea1.append("\n");
            for(int i=0;i<Library.getInstance().borrowers.get(row).UserLoanList.size();i++)
            {
                jTextArea1.append("Loan Item id: ");
                jTextArea1.append(String.valueOf(Library.getInstance().borrowers.get(row).UserLoanList.get(i).ItemId));
                jTextArea1.append("Due Date: ");
                jTextArea1.append(String.valueOf(Library.getInstance().borrowers.get(row).UserLoanList.get(i).duedate));
                jTextArea1.append("Issue Date: ");
                jTextArea1.append(String.valueOf(Library.getInstance().borrowers.get(row).UserLoanList.get(i).issuedate));
                jTextArea1.append("\n");
            }
            for(int i=0;i<Library.getInstance().borrowers.get(row).UserHoldList.size();i++)
            {
                jTextArea1.append("Hold Item id: ");
                jTextArea1.append(String.valueOf(Library.getInstance().borrowers.get(row).UserHoldList.get(i).HoldItem));
                jTextArea1.append("\n");
            }
    }//GEN-LAST:event_ViewButtonMouseClicked

    private void HoldButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoldButtonMouseClicked
            dbConnectivity con=new dbConnectivity();
            int id=Integer.valueOf(HoldTextField.getText());
            con.insertOnHold(this.id,id);
            OnHold h=new OnHold(this.id,id);
            int row=0;
            for(int i=0;i<Library.getInstance().borrowers.size();i++)
            {
                if(Library.getInstance().borrowers.get(i).id==id)
                    row=i;
            }
            Library.getInstance().borrowers.get(row).UserHoldList.add(h);
    }//GEN-LAST:event_HoldButtonMouseClicked

    private void SearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseClicked
        if(SubjectRadioButton.isSelected())
        {
            String s=SearchTextField.getText();
            for(int i=0;i<Library.getInstance().Items.size();i++)
            {
                if(s.equals(Library.getInstance().Items.get(i).subject))
                {
                    jTextArea1.append(String.valueOf(Library.getInstance().Items.get(i).id));
                    jTextArea1.append("  ");
                    jTextArea1.append(Library.getInstance().Items.get(i).title);
                    jTextArea1.append("\nIssued:  ");
                    jTextArea1.append(String.valueOf(Library.getInstance().Items.get(i).issued));
                     jTextArea1.append("\n");
                }
            }
        }
        else if(TitleRadioButton.isSelected())
        {
            String s=SearchTextField.getText();
            for(int i=0;i<Library.getInstance().Items.size();i++)
            {
                if(s.equals(Library.getInstance().Items.get(i).title))
                {
                    jTextArea1.append(String.valueOf(Library.getInstance().Items.get(i).id));
                    jTextArea1.append("  ");
                    jTextArea1.append(Library.getInstance().Items.get(i).subject);
                    jTextArea1.append("\nIssued:  ");
                    jTextArea1.append(String.valueOf(Library.getInstance().Items.get(i).issued));
                     jTextArea1.append("\n");
                }
            }
        }
    }//GEN-LAST:event_SearchButtonMouseClicked

    private void RenewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RenewButtonMouseClicked
        String date = RenewDateTextField.getText();
        int id = Integer.valueOf(RenewItemTextField.getText());
        int itemid = Integer.valueOf(ItemidTextField.getText());
        dbConnectivity con=new dbConnectivity();
        con.ExtendDate(id,itemid,date);
        Library.getInstance().LoanList = con.getBorrowerLoanList();
    }//GEN-LAST:event_RenewButtonMouseClicked

    private void PayFineButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayFineButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PayFineButtonMouseEntered

    private void PayFineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayFineButtonMouseClicked
        int id = Integer.valueOf(PayFineTextField.getText());
        dbConnectivity con=new dbConnectivity();
        con.PayFine(id);
        for(int i=0;i<Library.getInstance().borrowers.size();i++)
        {
            if(Library.getInstance().borrowers.get(i).id==id)
               Library.getInstance().borrowers.get(i).feeClear=true; 
        }
    }//GEN-LAST:event_PayFineButtonMouseClicked

    private void AddBorrowerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBorrowerButtonMouseClicked
                               java.awt.EventQueue.invokeLater(new Runnable() {
                                public void run() {
                                new AddABorrowerGUI().setVisible(true);
                            }
                            });
    }//GEN-LAST:event_AddBorrowerButtonMouseClicked

    private void RemoveBorrowerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveBorrowerButtonMouseClicked
        int id = Integer.valueOf(RemoveBorrowerNameTextField.getText());
        dbConnectivity con=new dbConnectivity();
        con.deleteBorrower(id);
        for(int i=0;i<Library.getInstance().borrowers.size();i++)
        {
            if(Library.getInstance().borrowers.get(i).id==id)
               Library.getInstance().borrowers.remove(i); 
        }
    }//GEN-LAST:event_RemoveBorrowerButtonMouseClicked

    private void UpdateBorrowerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBorrowerButtonMouseClicked
        int id = Integer.valueOf(UpdateBorrowerNameTextField.getText());
        String a = UpdateAddressTextField.getText();
        String p = UpdatephoneTextField.getText();
        dbConnectivity con=new dbConnectivity();
        con.updateBorrower(id,a,p);
        
        Library.getInstance().borrowers = con.getAllBorrowers();
    }//GEN-LAST:event_UpdateBorrowerButtonMouseClicked

    private void CheckOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckOutButtonMouseClicked
        dbConnectivity con=new dbConnectivity();

        int is =Integer.valueOf(LoanItemTextField.getText());

            for(int i=0;i<Library.getInstance().Items.size();i++)
            {
                if(Library.getInstance().Items.get(i).id==is)
                {
                    if(Library.getInstance().Items.get(i).issued==true)
                    {
                        
        JOptionPane.showMessageDialog(null,"Error","Checkout Item failed",JOptionPane.PLAIN_MESSAGE);
        return;
                    }
                }
            }
        
        int Bid = Integer.valueOf(LoanNameTextField.getText());
        String i = IssuedDateTextField.getText();
        String d = LoanDateTextField.getText();
        con.IssueItem(is);
        con.insertLoan(Bid,is,d,i);
                Library.getInstance().LoanList = con.getBorrowerLoanList();
        
        Library.getInstance().Items = con.getItems();
    }//GEN-LAST:event_CheckOutButtonMouseClicked

    private void ChecinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChecinButtonMouseClicked
        dbConnectivity con=new dbConnectivity();

        int is =Integer.valueOf(CheckinItemTextField.getText());

            for(int i=0;i<Library.getInstance().Items.size();i++)
            {
                if(Library.getInstance().Items.get(i).id==is)
                {
                    if(Library.getInstance().Items.get(i).issued==false)
                    {
                        
        JOptionPane.showMessageDialog(null,"Error","No One took it",JOptionPane.PLAIN_MESSAGE);
        return;
                    
                    }
                    else
                    {
                                int Bid = Integer.valueOf(CheckinNameTextField.getText());
        con.UnIssueItem(is);
        con.Checkin(Bid, is);
                    }
                }
            }
    }//GEN-LAST:event_ChecinButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClerkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClerkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClerkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClerkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClerkGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBorrowerButton;
    private javax.swing.JButton ChecinButton;
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JTextField CheckinItemTextField;
    private javax.swing.JTextField CheckinNameTextField;
    private javax.swing.JButton HoldButton;
    private javax.swing.JTextField HoldTextField;
    private javax.swing.JTextField IssuedDateTextField;
    private javax.swing.JTextField ItemidTextField;
    private javax.swing.JTextField LoanDateTextField;
    private javax.swing.JTextField LoanItemTextField;
    private javax.swing.JTextField LoanNameTextField;
    private javax.swing.JButton PayFineButton;
    private javax.swing.JTextField PayFineTextField;
    private javax.swing.JButton RemoveBorrowerButton;
    private javax.swing.JTextField RemoveBorrowerNameTextField;
    private javax.swing.JButton RenewButton;
    private javax.swing.JTextField RenewDateTextField;
    private javax.swing.JTextField RenewItemTextField;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JRadioButton SubjectRadioButton;
    private javax.swing.JRadioButton TitleRadioButton;
    private javax.swing.JTextField UpdateAddressTextField;
    private javax.swing.JButton UpdateBorrowerButton;
    private javax.swing.JTextField UpdateBorrowerNameTextField;
    private javax.swing.JTextField UpdatephoneTextField;
    private javax.swing.JButton ViewButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
